# ------------------- Stage 1: Build Stage ------------------------------

# BASE IMAGE
 
FROM python:3.9 AS builder

# WORKING DIRECTORY

WORKDIR /app

# INSTALL REQUIRE PACKAGES FOR SYSTEM

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc default-libmysqlclient-dev pkg-config && \
    rm -rf /var/lib/apt/lists/*

# COPY THE REQUIREMENT FILE INTO CONTAINER

COPY requirements.txt .

# INSTALLAPP DEPENDENCIES
RUN pip install mysqlclient
RUN pip install --no-cache-dir -r requirements.txt

# ------------------- Stage 2: Final Stage ------------------------------

# BASE IMAGE

FROM python:3.9-slim

# WORKING DIRECTORY

WORKDIR /app

# Install runtime dependencies only

RUN apt-get update && \
    apt-get install -y --no-install-recommends libmariadb3 && \
    rm -rf /var/lib/apt/lists/*

# Copy dependencies and application code from the builder stage
COPY --from=builder /usr/local/lib/python3.9/site-packages/ /usr/local/lib/python3.9/site-packages/
COPY . .

#RUN APP

CMD ["python", "app.py"]
