

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: bankdb
      MYSQL_ROOT_HOST: '%'
    networks:
      - bankapp
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pTest@123"]
      interval: 10s
      retries: 5
      start_period: 60s
    restart: always
  bankapp:
    container_name: bankapp
    image: heyitsmeabhishek/bankapp
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test@123
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bankdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    networks:
      - bankapp
    depends_on:
      - mysql
    restart: always

volumes:
  mysql-data:

networks:
  bankapp:
